sudo: required 
services:
    - docker

before_install:
    - docker build -t vokidoki130/docker-test -f ./client/Dockerfile.dev ./client

script:
    - docker run vokidoki130/docker-test npm test -- --coverage

after_success: 
    - docker build -t vokidoki130/multi-client ./client
    - docker build -t vokidoki130/multi-nginx  ./nginx
    - docker build -t vokidoki130/multi-server ./server
    - docker build -t vokidoki130/multi-worker ./worker
    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push vokidoki130/multi-client
    - docker push vokidoki130/multi-nginx
    - docker push vokidoki130/multi-server
    - docker push vokidoki130/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-999994026265
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
        
